new

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -166,27 +166,27 @@ jobs:
              # Step 9: Deploy and Configure Instanc
       - name: Deploy and Configure Instance
         run: |
-            ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.INSTANCE_IP }} <<'EOF'
-            set -x
-            trap 'echo "Error occurred at line $LINENO"; exit 1' ERR
-            # Run dpkg configuration
-            sudo dpkg --configure -a
-            # Update package lists and install Nginx
-            sudo apt-get update
-            sudo apt-get install -y nginx
-            # Install Certbot and Nginx plugin for SSL certificate management
-            sudo apt-get install -y certbot python3-certbot-nginx
-            # Enable and start Nginx service
-            sudo systemctl enable nginx
-            sudo systemctl start nginx
-            # Obtain SSL certificate with Certbot
-            sudo certbot --nginx -d ${{ secrets.DOMAIN_NAME }} --non-interactive --agree-tos --email ${{ secrets.EMAIL }}
-            # Test Nginx configuration
-            sudo nginx -t
-            # Reload Nginx service to apply changes
-            sudo systemctl reload nginx
-            EOF
-        
+                 ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.INSTANCE_IP }} <<'EOF'
+                 set -x
+                 trap 'echo "Error occurred at line $LINENO"; exit 1' ERR
+                 # Run dpkg configuration
+                 sudo dpkg --configure -a
+                 # Update package lists and install Nginx
+                 sudo apt-get update
+                 sudo apt-get install -y nginx
+                 # Install Certbot and Nginx plugin for SSL certificate management
+                 # sudo apt-get install -y certbot python3-certbot-nginx
+                 # Enable and start Nginx service
+                 sudo systemctl enable nginx
+                 sudo systemctl start nginx
+                 # Obtain SSL certificate with Certbot
+                 # sudo certbot --nginx -d ${{ secrets.DOMAIN_NAME }} --non-interactive --agree-tos --email ${{ secrets.EMAIL }}
+                 # Test Nginx configuration
+                 sudo nginx -t
+                 # Reload Nginx service to apply changes
+                 sudo systemctl reload nginx
+                 EOF
+           
       - name: Configure Nginx Reverse Proxy
         run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.INSTANCE_IP }} <<'EOF'
