new

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -108,48 +108,51 @@ jobs:
             INSTANCE_IP: ${{ secrets.INSTANCE_IP }}
             DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
             EMAIL: ${{ secrets.EMAIL }}
-        
 
       # Step 5: Configure Nginx Reverse Proxy
       - name: Configure Nginx Reverse Proxy for Frontend and Backend
         run: |
-          ssh -o StrictHostKeyChecking=no -i "/home/ubuntu/.ssh/id_rsa" ubuntu@${{ secrets.INSTANCE_IP }} <<'EOF'
-            set -x
-            trap 'echo "Error occurred at line $LINENO"' ERR
-            # Nginx Configuration
-            echo 'server {
-              listen 80;
-              server_name melvinsamuel070.xyz;
-              return 301 https://$host$request_uri;
-            }
-            server {
-              listen 443 ssl;
-              server_name melvinsamuel070.xyz;
-              ssl_certificate /etc/letsencrypt/live/melvinsamuel070.xyz/fullchain.pem;
-              ssl_certificate_key /etc/letsencrypt/live/melvinsamuel070.xyz/privkey.pem;
-              location / {
-                proxy_pass http://107.21.180.100:3000;
-                proxy_set_header Host $host;
-                proxy_set_header X-Real-IP $remote_addr;
-                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
-                proxy_set_header X-Forwarded-Proto $scheme;
-              }
-              location /api/ {
-                proxy_pass http://107.21.180.100:3500;
-                proxy_set_header Host $host;
-                proxy_set_header X-Real-IP $remote_addr;
-                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
-                proxy_set_header X-Forwarded-Proto $scheme;
-              }
-            }' | sudo tee /etc/nginx/sites-available/default > /dev/null
-            # Test Nginx configuration and reload
-            sudo nginx -t
-            sudo systemctl reload nginx
-            sudo systemctl start nginx
-            
-            set +x
-          EOF
-      # Step 6: Start Docker Compose on EC2 with Debugging
+         ssh -o StrictHostKeyChecking=no -i "/home/ubuntu/.ssh/id_rsa" ubuntu@${{ secrets.INSTANCE_IP }} <<'EOF'
+         set -x
+         trap 'echo "Error occurred at line $LINENO"' ERR
+                 
+         echo 'nginx ALL=(ALL) NOPASSWD:ALL' | sudo tee /etc/sudoers.d/nginx
+                                       
+         echo 'server {
+          listen 80;
+          server_name melvinsamuel070.xyz;
+          return 301 https://$host$request_uri;
+         }
+          server {
+          listen 443 ssl;
+          server_name melvinsamuel070.xyz;
+         # ssl_certificate /etc/letsencrypt/live/melvinsamuel070.xyz/fullchain.pem;
+         # ssl_certificate_key /etc/letsencrypt/live/melvinsamuel070.xyz/privkey.pem;
+          location / {
+            proxy_pass http://107.21.180.100:3000;
+            proxy_set_header Host $host;
+            proxy_set_header X-Real-IP $remote_addr;
+            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
+            proxy_set_header X-Forwarded-Proto $scheme;
+         }
+         location /api/ {
+           proxy_pass http://107.21.180.100:3500;
+           Host $host;
+           proxy_set_header X-Real-IP $remote_addr;
+           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
+           proxy_set_header X-Forwarded-Proto $scheme;
+         }
+         }' | sudo tee /etc/nginx/sites-available/default > /dev/null
+
+         # Test Nginx configuration and reload
+         sudo nginx -t
+         sudo systemctl reload nginx
+         sudo systemctl start nginx
+               
+         set +x
+         EOF
+    
+        # Step 6: Start Docker Compose on EC2 with Debugging
       - name: Start Docker Compose on EC2 with Debugging
         run: |
           ssh -o StrictHostKeyChecking=no -i "/home/ubuntu/.ssh/id_rsa" ubuntu@${{ secrets.INSTANCE_IP }} <<'EOF'
