new

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -207,35 +207,32 @@ jobs:
          sudo systemctl reload nginx
          EOF
 
-         # Step 6: Start Docker Compose on EC2 with Debugging
+           # Step 6: Start Docker Compose on EC2 with Debugging
       - name: Start Docker Compose on EC2 with Debugging
         run: |
-         ssh -o StrictHostKeyChecking=no -i "/home/ubuntu/.ssh/id_rsa" ubuntu@${{ secrets.INSTANCE_IP }} <<'EOF'
-         set -x
-         trap 'echo "Error occurred at line $LINENO"' ERR
-
-         # Resolve any dpkg lock issues before starting Docker installation
-         sudo dpkg --configure -a
-         sudo apt-get install -f -y  # Attempt to fix broken dependencies
-
-         # Update package lists
-         sudo apt-get update
-
-         # Check if Docker and Docker Compose are installed, and install if necessary
-         if ! command -v docker &> /dev/null; then
-         echo "Docker not found, installing..."
-         sudo apt-get install -y docker.io
-         fi
-         if ! command -v docker-compose &> /dev/null; then
-         echo "Docker Compose not found, installing..."
-         sudo apt-get install -y docker-compose
-         fi
-
-         # Navigate to app directory and start Docker Compose with more memory
-         cd /home/ubuntu/MERN_Todo_app
-         NODE_OPTIONS=--max-old-space-size=4096 sudo docker-compose up -d
-         set +x
-         EOF
+          ssh -o StrictHostKeyChecking=no -i "/home/ubuntu/.ssh/id_rsa" ubuntu@${{ secrets.INSTANCE_IP }} <<'EOF'
+            set -x
+            trap 'echo "Error occurred at line $LINENO"' ERR
+            # Resolve any dpkg lock issues before starting Docker installation
+            sudo dpkg --configure -a
+            sudo apt-get install -f -y  # Attempt to fix broken dependencies
+            # Update package lists
+            sudo apt-get update
+            # Check if Docker and Docker Compose are installed, and install if necessary
+            if ! command -v docker &> /dev/null; then
+              echo "Docker not found, installing..."
+              sudo apt-get install -y docker.io
+            fi
+            if ! command -v docker-compose &> /dev/null; then
+              echo "Docker Compose not found, installing..."
+              sudo apt-get install -y docker-compose
+            fi
+            # Navigate to project directory and start Docker Compose
+            cd /home/ubuntu/MERN_Todo_app
+            sudo docker compose up -d
+            set +x
+          EOF
+         
 
       - name: Notify Pushgateway about pipeline progress (start)
         run: |
