new

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,115 +1,112 @@
-name: CI Pipeline
+name: CD Pipeline
 
 on:
-  push:
-    branches:
-      - main
-    paths-ignore:
-      - '**/*.md'
   workflow_dispatch:
+    inputs:
+      event_type:
+        description: 'Event to trigger deployment'
+        required: true
+        default: 'start_cd_pipeline'
 
 env:
+  AWS_REGION: us-east-1
   BACKEND_IMAGE: melvinsamuel070/backend:latest
   FRONTEND_IMAGE: melvinsamuel070/frontend1:latest
   ALERTMANAGER_URL: http://localhost:9092/api/v2/alerts
+  DOMAIN: melvinsamuel070.xyz  # Replace this with your actual domain
 
 jobs:
-  build:
+  deploy:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout Code
-        uses: actions/checkout@v2
-        id: checkout
-      
-      - name: Print Debug Info - Branch and Commit
-        run: |
-          echo "Branch: ${{ github.ref }}"
-          echo "Commit: ${{ github.sha }}"
-
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v1
-
-      - name: Build Backend Image
-        run: docker build -t ${{ env.BACKEND_IMAGE }} -f ./backend/Dockerfile ./backend
-
-      - name: Build Frontend Image
-        run: docker build -t ${{ env.FRONTEND_IMAGE }} -f ./frontend/Dockerfile ./frontend
-
-      - name: Upload Build Logs
-        if: always()
-        uses: actions/upload-artifact@v3
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v1
         with:
-          name: build-logs
-          path: |
-            ./backend/build.log
-            ./frontend/build.log
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ env.AWS_REGION }}
 
-      - name: Login to Docker Hub
-        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
-
-      - name: Push Backend Image to Docker Hub
-        run: docker push ${{ env.BACKEND_IMAGE }}
-
-      - name: Start Alertmanager
+      - name: Set up SSH key
         run: |
-          docker run -d -p 9092:9093 --name alertmanager prom/alertmanager:v0.27.0
+          mkdir -p ~/.ssh
+          echo "$AWS_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
+          chmod 600 ~/.ssh/id_rsa
+          ssh-keyscan -H ${{ secrets.INSTANCE_IP }} >> ~/.ssh/known_hosts
+        env:
+          AWS_SSH_PRIVATE_KEY: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
 
-      - name: Wait for Alertmanager to be ready
+      - name: Connect to EC2 Instance and Install Dependencies
         run: |
-          for i in {1..10}; do 
-            if curl -s -f http://localhost:9092; then 
-              echo "Alertmanager is up and running!"; 
-              break; 
-            fi; 
-            echo "Waiting for Alertmanager to be ready..."; 
-            sleep 6; 
-          done
+          ssh -o StrictHostKeyChecking=no -i "/home/ubuntu/.ssh/id_rsa" ubuntu@${{ secrets.INSTANCE_IP }} << 'EOF'
+            # Update DNS settings to improve network reliability
+            echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null
+            echo "nameserver 1.1.1.1" | sudo tee -a /etc/resolv.conf > /dev/null
 
-      - name: Notify Alertmanager of Build Success
+            # Ensure hostname resolution
+            sudo sed -i "1s/^/127.0.0.1 $(hostname)\n/" /etc/hosts
+
+            # Install Docker and Docker Compose
+            sudo apt-get update
+            sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
+            sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
+            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
+            sudo apt-get update
+            sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose
+
+            # Enable Docker service
+            sudo systemctl enable docker
+            sudo systemctl start docker
+          EOF
+
+      - name: Test Nginx Configuration
         run: |
-            response=$(curl -s -o /dev/null -w "%{http_code}" -X POST -H "Content-Type: application/json" -d '[
-              {
-                "labels": {
-                  "alertname": "BuildSuccess",
-                  "severity": "info",
-                  "team": "development",
-                  "environment": "production"
-                },
-                "annotations": {
-                  "summary": "Build Successful",
-                  "description": "The latest build was successful."
+          ssh -o StrictHostKeyChecking=no -i "/home/ubuntu/.ssh/id_rsa" ubuntu@${{ secrets.INSTANCE_IP }} << 'EOF'
+            sudo nginx -t || exit 1
+          EOF
+
+      - name: Configure Nginx as Reverse Proxy
+        run: |
+          ssh -o StrictHostKeyChecking=no -i "/home/ubuntu/.ssh/id_rsa" ubuntu@${{ secrets.INSTANCE_IP }} << 'EOF'
+            sudo tee /etc/nginx/sites-available/default > /dev/null << 'CONFIG'
+              server {
+                listen 80;
+                server_name ${{ env.DOMAIN }};
+    
+                location / {
+                  proxy_pass http://localhost:3000;
+                  proxy_set_header Host $host;
+                  proxy_set_header X-Real-IP $remote_addr;
+                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
+                }
+
+                location /api/ {
+                   proxy_pass http://localhost:3500/;
+                   proxy_set_header Host $host;
+                   proxy_set_header X-Real-IP $remote_addr;
+                   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                 }
               }
-            ]' http://localhost:9092/api/v2/alerts)
-        
-            echo "Response Code: $response"
-        
-            if [ "$response" -ne 200 ]; then
-              echo "Failed to notify Alertmanager: HTTP Status $response"
-              exit 1
-            else
-              echo "Successfully notified Alertmanager of build success."
-            fi
-        
-      - name: Send Email Notification for Build Success
+            CONFIG
+            sudo nginx -t || {echo "Nginx configuration error detected."; exit 1;}
+            sudo systemctl restart nginx
+          EOF
+
+      - name: Secure Nginx with SSL (Certbot)
+        run: |
+          ssh -o StrictHostKeyChecking=no -i "/home/ubuntu/.ssh/id_rsa" ubuntu@${{ secrets.INSTANCE_IP }} << 'EOF'
+            sudo apt update
+            sudo apt install -y certbot python3-certbot-nginx
+            sudo certbot --nginx --non-interactive --agree-tos --email ${{ secrets.EMAIL_USERNAME }} -d ${{ env.DOMAIN }}
+          EOF
+
+      - name: Send Email Notification for Deployment Success
         uses: dawidd6/action-send-mail@v3
         with:
-            server_address: smtp.gmail.com
-            server_port: 587
-            username: ${{ secrets.EMAIL_USERNAME }}
-            password: ${{ secrets.EMAIL_PASSWORD }}
-            subject: "Build Success: CI Pipeline"
-            body: "The build stage of your CI pipeline completed successfully."
-            to: kingsamuel412@gmail.com
-            from: ${{ secrets.EMAIL_USERNAME }}
-
-  trigger_cd:
-    needs: build
-    runs-on: ubuntu-latest
-    steps:
-      - name: Trigger CD Pipeline
-        run: |
-          curl -X POST \
-            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-            -d '{"event_type": "start_cd_pipeline"}' \
-            "https://api.github.com/repos/${{ github.repository }}/dispatches"
+          server_address: smtp.gmail.com
+          server_port: 587
+          username: ${{ secrets.EMAIL_USERNAME }}
+          password: ${{ secrets.EMAIL_PASSWORD }}
+          subject: "Deployment Success: CD Pipeline"
+          body: "The deployment of your application completed successfully."
+          to: kingsamuel412@gmail.com
+          from: ${{ secrets.EMAIL_USERNAME }}
