new

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -192,14 +192,12 @@ jobs:
           echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin || { echo "Docker login failed"; exit 1; }
 
       - name: Push Backend Image to Docker Hub
-        run: |
-          echo "Pushing Backend image to Docker Hub..."
-          docker push ${{ secrets.BACKEND_IMAGE }} || { echo "Docker push for Backend failed"; exit 1; }
-
+        run: echo "Pushing Backend image to Docker Hub..." && docker push ${{ secrets.BACKEND_IMAGE }} || (echo "Docker push failed" && exit 1)
+        
       - name: Push Frontend Image to Docker Hub
         run: |
-          echo "Pushing Frontend image to Docker Hub..."
-          docker push ${{ secrets.FRONTEND_IMAGE }} || { echo "Docker push for Frontend failed"; exit 1; }
+           echo "Pushing Frontend image to Docker Hub..."
+           docker push ${{ secrets.FRONTEND_IMAGE }} || { echo "Docker push for Frontend failed"; exit 1; }
 
       - name: Start Alertmanager (If Needed)
         run: |
