new

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -55,36 +55,40 @@ jobs:
         run: |
           docker run -d -p 9092:9093 --name alertmanager prom/alertmanager:v0.27.0
 
-      - name: Notify Alertmanager of Build Success
-        env:
-          ALERTMANAGER_URL: http://localhost:9092/api/v2/alerts
+      - name: Wait for Alertmanager to be ready
         run: |
-          echo "Sending build success notification to Alertmanager..."
-          response=$(curl --retry 3 --retry-delay 5 --max-time 30 -v -X POST -H "Content-Type: application/json" -d '[
-            {
-              "labels": {
-                "alertname": "BuildSuccess",
-                "severity": "info",
-                "team": "development",
-                "environment": "production"
-              },
-              "annotations": {
-                "summary": "Build Successful",
-                "description": "The latest build was successful."
+          for i in {1..10}; do 
+            if curl -s -f http://localhost:9092; then 
+              echo "Alertmanager is up and running!"; 
+              break; 
+            fi; 
+            echo "Waiting for Alertmanager to be ready..."; 
+            sleep 6; 
+          done
+
+      - name: Notify Alertmanager of Build Success
+        run: |
+            response=$(curl -s -o /dev/null -w "%{http_code}" -X POST -H "Content-Type: application/json" -d '[
+              {
+                "labels": {
+                  "alertname": "BuildSuccess",
+                  "severity": "info",
+                  "team": "development",
+                  "environment": "production"
+                },
+                "annotations": {
+                  "summary": "Build Successful",
+                  "description": "The latest build was successful."
+                }
               }
-            }
-          ]' $ALERTMANAGER_URL 2>&1)
-      
-          echo "Response from Alertmanager:"
-          echo "$response"
-          
-          if [[ "$response" == *"Failed"* || "$response" == *"error"* || "$response" == *"refused"* || "$response" == *"connection"* ]]; then
-            echo "Error occurred while sending notification to Alertmanager."
-            echo "Full response: $response"
-            exit 1
-          else
-            echo "Successfully sent notification to Alertmanager."
-          fi
+            ]' http://localhost:9092/api/v2/alerts)
+            
+            if [ "$response" -ne 200 ]; then
+              echo "Failed to notify Alertmanager: HTTP Status $response"
+              exit 1
+            else
+              echo "Successfully notified Alertmanager of build success."
+            fi
 
       - name: Send Email Notification for Build Success
         uses: dawidd6/action-send-mail@v3
